site_name: odsclient
# site_description: 'A short description of my project'
repo_url: https://github.com/smarie/python-odsclient
docs_dir: .
site_dir: ../site
nav:
    - Home: index.md
    - odskey command: odskey.md
    - API reference: api_reference.md
    - Changelog: changelog.md

theme: material  # readthedocs  mkdocs

markdown_extensions:
  - admonition  # to add notes such as http://squidfunk.github.io/mkdocs-material/extensions/admonition/
  - codehilite:
      guess_lang: true
  - toc:
      permalink: true